name: e_commerce_application
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


#-------------PACKAGES------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  leak_tracker: ^10.0.0

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7
  cached_network_image: ^3.3.1




  #---------- ./ PACKAGES END ----------#

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #----------- LOCAL ASSETS ----------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/user/
    - assets/icons/payment_methods/


  #----------- LOCAL FONTS ----------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
